"""create core tables

Revision ID: eb0bf72130d2
Revises:
Create Date: 2026-10-09 13:33:36.587794

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import glucobalance.models.types

# revision identifiers, used by Alembic.
revision: str = "eb0bf72130d2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "body_sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column(
            "region",
            sa.Enum(
                "abdomen",
                "thigh",
                "arm",
                "buttock",
                name="siteregion",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "side",
            sa.Enum("left", "right", name="bodyside", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "view",
            sa.Enum("front", "back", name="bodyview", native_enum=False, length=32),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_body_sites")),
        sa.UniqueConstraint("code", name=op.f("uq_body_sites_code")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at", glucobalance.models.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "carb_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("eaten_at", glucobalance.models.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("grams", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.CheckConstraint("grams > 0", name=op.f("ck_carb_entries_grams_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_carb_entries_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carb_entries")),
    )
    with op.batch_alter_table("carb_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_carb_entries_eaten_at"), ["eaten_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_carb_entries_user_id"), ["user_id"], unique=False)

    op.create_table(
        "glucose_readings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "measured_at", glucobalance.models.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("value_mgdl", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "manual", "cgm", "simulated", name="readingsource", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "tag",
            sa.Enum(
                "fasting",
                "before_meal",
                "after_meal",
                "bedtime",
                "night",
                name="glucosetag",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "trend",
            sa.Enum(
                "falling_fast",
                "falling",
                "steady",
                "rising",
                "rising_fast",
                name="trend",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.CheckConstraint("value_mgdl > 0", name=op.f("ck_glucose_readings_value_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_glucose_readings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_glucose_readings")),
        sa.UniqueConstraint(
            "user_id", "source", "measured_at", name=op.f("uq_glucose_readings_user_id")
        ),
    )
    with op.batch_alter_table("glucose_readings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_glucose_readings_measured_at"), ["measured_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_glucose_readings_user_id"), ["user_id"], unique=False)

    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("noted_at", glucobalance.models.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notes")),
    )
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notes_noted_at"), ["noted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_notes_user_id"), ["user_id"], unique=False)

    op.create_table(
        "reminders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "set_change",
                "reservoir",
                "long_acting_dose",
                "pen_needle",
                "pen_expiry",
                "glucose_check",
                "sensor_change",
                "custom",
                name="reminderkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=True),
        sa.Column("time_of_day", sa.Time(), nullable=True),
        sa.Column(
            "next_due_at", glucobalance.models.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "interval_days IS NULL OR interval_days > 0",
            name=op.f("ck_reminders_interval_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_reminders_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminders")),
    )
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reminders_user_id"), ["user_id"], unique=False)

    op.create_table(
        "site_uses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("used_at", glucobalance.models.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "infusion_set",
                "rapid_injection",
                "long_injection",
                "cgm_sensor",
                name="sitepurpose",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["body_sites.id"], name=op.f("fk_site_uses_site_id_body_sites")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_site_uses_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_uses")),
    )
    with op.batch_alter_table("site_uses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_site_uses_used_at"), ["used_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_site_uses_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "delivery_mode",
            sa.Enum("pump", "pens", name="deliverymode", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "monitoring_mode",
            sa.Enum("glucometer", "cgm", name="monitoringmode", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "display_unit",
            sa.Enum("mg/dL", "mmol/L", name="displayunit", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("target_low_mgdl", sa.Integer(), nullable=False),
        sa.Column("target_high_mgdl", sa.Integer(), nullable=False),
        sa.Column("insulin_action_minutes", sa.Integer(), nullable=False),
        sa.Column("max_bolus_units", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("dose_step_units", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("clinician_contact", sa.Text(), nullable=True),
        sa.CheckConstraint("dose_step_units > 0", name=op.f("ck_user_settings_dose_step_positive")),
        sa.CheckConstraint(
            "insulin_action_minutes > 0", name=op.f("ck_user_settings_insulin_action_positive")
        ),
        sa.CheckConstraint("max_bolus_units > 0", name=op.f("ck_user_settings_max_bolus_positive")),
        sa.CheckConstraint(
            "target_low_mgdl < target_high_mgdl", name=op.f("ck_user_settings_target_range_order")
        ),
        sa.CheckConstraint(
            "target_low_mgdl > 0", name=op.f("ck_user_settings_target_low_positive")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_settings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_settings")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_settings_user_id")),
    )
    op.create_table(
        "insulin_doses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("taken_at", glucobalance.models.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("units", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "insulin_type",
            sa.Enum("rapid", "long", name="insulintype", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum("bolus", "correction", "basal", name="dosekind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("site_use_id", sa.Integer(), nullable=True),
        sa.CheckConstraint("units > 0", name=op.f("ck_insulin_doses_units_positive")),
        sa.ForeignKeyConstraint(
            ["site_use_id"],
            ["site_uses.id"],
            name=op.f("fk_insulin_doses_site_use_id_site_uses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_insulin_doses_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insulin_doses")),
    )
    with op.batch_alter_table("insulin_doses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_insulin_doses_taken_at"), ["taken_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_insulin_doses_user_id"), ["user_id"], unique=False)

    op.create_table(
        "settings_time_blocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("settings_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("icr_grams_per_unit", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column("isf_mgdl", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "icr_grams_per_unit > 0", name=op.f("ck_settings_time_blocks_icr_positive")
        ),
        sa.CheckConstraint("isf_mgdl > 0", name=op.f("ck_settings_time_blocks_isf_positive")),
        sa.ForeignKeyConstraint(
            ["settings_id"],
            ["user_settings.id"],
            name=op.f("fk_settings_time_blocks_settings_id_user_settings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings_time_blocks")),
        sa.UniqueConstraint(
            "settings_id", "start_time", name=op.f("uq_settings_time_blocks_settings_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings_time_blocks")
    with op.batch_alter_table("insulin_doses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_insulin_doses_user_id"))
        batch_op.drop_index(batch_op.f("ix_insulin_doses_taken_at"))

    op.drop_table("insulin_doses")
    op.drop_table("user_settings")
    with op.batch_alter_table("site_uses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_site_uses_user_id"))
        batch_op.drop_index(batch_op.f("ix_site_uses_used_at"))

    op.drop_table("site_uses")
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reminders_user_id"))

    op.drop_table("reminders")
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notes_user_id"))
        batch_op.drop_index(batch_op.f("ix_notes_noted_at"))

    op.drop_table("notes")
    with op.batch_alter_table("glucose_readings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_glucose_readings_user_id"))
        batch_op.drop_index(batch_op.f("ix_glucose_readings_measured_at"))

    op.drop_table("glucose_readings")
    with op.batch_alter_table("carb_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_carb_entries_user_id"))
        batch_op.drop_index(batch_op.f("ix_carb_entries_eaten_at"))

    op.drop_table("carb_entries")
    op.drop_table("users")
    op.drop_table("body_sites")
    # ### end Alembic commands ###
