"""add favourite meals and hypo treatments

Revision ID: e94218bd9b7f
Revises: 76bce437796c
Create Date: 2026-10-09 14:41:22.697319

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import glucobalance.models.types

# revision identifiers, used by Alembic.
revision: str = "e94218bd9b7f"
down_revision: str | Sequence[str] | None = "76bce437796c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favourite_meals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("grams", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.CheckConstraint("grams > 0", name=op.f("ck_favourite_meals_grams_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_favourite_meals_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_favourite_meals")),
        sa.UniqueConstraint("user_id", "name", name=op.f("uq_favourite_meals_user_id")),
    )
    with op.batch_alter_table("favourite_meals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_favourite_meals_user_id"), ["user_id"], unique=False)

    op.create_table(
        "hypo_treatments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "treated_at", glucobalance.models.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "treatment",
            sa.Enum(
                "glucose_tablets",
                "juice",
                "sweets",
                "food",
                "glucagon",
                "other",
                name="hypotreatmentkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("carbs_grams", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("reading_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.CheckConstraint(
            "carbs_grams IS NULL OR carbs_grams > 0", name=op.f("ck_hypo_treatments_carbs_positive")
        ),
        sa.ForeignKeyConstraint(
            ["reading_id"],
            ["glucose_readings.id"],
            name=op.f("fk_hypo_treatments_reading_id_glucose_readings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_hypo_treatments_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hypo_treatments")),
    )
    with op.batch_alter_table("hypo_treatments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_hypo_treatments_treated_at"), ["treated_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_hypo_treatments_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hypo_treatments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hypo_treatments_user_id"))
        batch_op.drop_index(batch_op.f("ix_hypo_treatments_treated_at"))

    op.drop_table("hypo_treatments")
    with op.batch_alter_table("favourite_meals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_favourite_meals_user_id"))

    op.drop_table("favourite_meals")
    # ### end Alembic commands ###
