"""add timezone and reading note

Revision ID: 76bce437796c
Revises: d00e1d9784a5
Create Date: 2026-10-09 13:29:10.529530

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76bce437796c"
down_revision: str | Sequence[str] | None = "d00e1d9784a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("glucose_readings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("note", sa.String(length=500), nullable=True))

    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.drop_column("timezone")

    with op.batch_alter_table("glucose_readings", schema=None) as batch_op:
        batch_op.drop_column("note")

    # ### end Alembic commands ###
