"""add password hash and settings changes

Revision ID: d00e1d9784a5
Revises: eb0bf72130d2
Create Date: 2026-10-09 12:24:53.774323

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import glucobalance.models.types

# revision identifiers, used by Alembic.
revision: str = "d00e1d9784a5"
down_revision: str | Sequence[str] | None = "eb0bf72130d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings_changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("changed_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "changed_at", glucobalance.models.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("field", sa.String(length=64), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "onboarding",
                "user",
                "assistant_suggestion",
                name="changesource",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_id"],
            ["users.id"],
            name=op.f("fk_settings_changes_changed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_settings_changes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings_changes")),
    )
    with op.batch_alter_table("settings_changes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_settings_changes_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("password_hash", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("password_hash")

    with op.batch_alter_table("settings_changes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_settings_changes_user_id"))

    op.drop_table("settings_changes")
    # ### end Alembic commands ###
